const APPS_LIST = [
    { i: "soutijing", n: "搜题酱", u: "soutijing", p: "i", c: "a" },
    { i: "oldtiktok", n: "旧版抖音", u: "oldtiktokipa", p: "i", c: "a" },
    { i: "biliwear", n: "biliwear", u: "biliwearapk", p: "a", c: "a" },
    { i: "shizuku", n: "shizuku", u: "shizukumapk", p: "a", c: "a" },
    { i: "pilipala-android", n: "pilipala", u: "pilipalaapk", p: "a", c: "a" },
    { i: "pilipala-ios", n: "pilipala", u: "pilipalaipa", p: "i", c: "a" },
    { i: "oldbili", n: "旧版bili", u: "oldbiliipa", p: "i", c: "a" },
    { i: "troll", n: "TrollInstallerX", u: "Trollipa", p: "i", c: "a" },
    { i: "pilipius", n: "PiliPlus", u: "ZesgWep9", p: "a", c: "a" },
    { i: "handnote-reader", n: "手记 (GT Fit阅读器)", u: "mPkecEbW", p: "a", c: "a" },
    { i: "afusekt", n: "AfuseKt", u: "FJw0UOgj", p: "a", c: "a" },
    { i: "huawei-health", n: "华为运动健康", u: "xb2Bi9dy", p: "a", c: "a" },
    { i: "gtasa-ios", n: "侠盗猎车手：圣安地列斯", u: "gtasaipag", p: "i", c: "g" },
    { i: "gtasa-android", n: "侠盗猎车手：圣安地列斯", u: "gtasaapkg", p: "a", c: "g" },
    { i: "minecraft-ios", n: "我的世界", u: "Minecraftgipa", p: "i", c: "g" },
    { i: "terraria", n: "泰拉瑞亚", u: "terraria", p: "i", c: "g" },
    { i: "stardewvalley", n: "星露谷物语", u: "stardewvalley", p: "i", c: "g" },
    { i: "winlator", n: "Winlator", u: "TfC7fctK", p: "a", c: "a" },
    { i: "slay-the-spire-2", n: "杀戮尖塔2", u: "D52gSKc3", p: "a", c: "g" },
    { i: "minecraft-android", n: "我的世界", u: "qBF7UmHd", p: "a", c: "g" },
    { i: "virtual-master", n: "虚拟大师", u: "GeRzhAns", p: "a", c: "a" },
    { i: "installerx", n: "InstallerX", u: "6aLMvgmu", p: "a", c: "a" },
    { i: "lspatch", n: "LSPatch", u: "nhYH3CKa", p: "a", c: "a" },
    { i: "ice-box", n: "冰箱", u: "o2NSrURB", p: "a", c: "a" },
    { i: "mt-manager", n: "MT管理器", u: "oVVAMbpR", p: "a", c: "a" },
    { i: "mahiro-browser", n: "MahiroBrowser", u: "t4ww2VRN", p: "a", c: "a" },
    { i: "moonlight-plus", n: "月光-威力加强版", u: "SAHwQnCc", p: "a", c: "a" },
    { i: "wearos-toolbox", n: "WearOS Toolbox", u: "vVyf5w3Z", p: "a", c: "a" },
    { i: "gif-live-wallpaper", n: "GIF 动态壁纸", u: "PciBD35o", p: "a", c: "a" },
    { i: "dunlun-tiaodiao", n: "敦伦调调", u: "XLS1ZMsu", p: "a", c: "a" },
    { i: "wearripple-lite", n: "WearRippleLite", u: "0UPUcpqu", p: "a", c: "a" }
];